# Generated by Django 3.1.7 on 2021-03-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3000, verbose_name='Question')),
                ('options', models.CharField(max_length=3000, verbose_name='Options')),
                ('correct_option', models.CharField(max_length=300, verbose_name='Correct option. Max 300 characters')),
                ('points', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
